
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - cloudflared
    environment:
      - API_KEY
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --url http://app:8000 --token ${TUNNEL_TOKEN}
    environment:
      - TUNNEL_TOKEN
